### ISSUE TITLE
Manage the layout for devices having width less than 450px

### ISSUE THREAD

**Issue by sabique** [sabique/Booking-App-using-Flexbox#12]
Manage the hotel overview section layout for the devices having a width less than 450px.

![Screenshot_2019-10-05-15-48-28-667_com duckduckgo mobile android](https://user-images.githubusercontent.com/8267052/66253542-c8faed80-e787-11e9-89b7-b5d0f640c0b6.png)

**Comment by thewhiteswan** [comment]
Hi @sabique I gave it a shot let me know what you think! #15

**Comment by sabique** [comment]
Hi, @thewhiteswan I will check the changes asap and share my feedback. Thanks!

**Comment by sabique** [comment]
The issue has been fixed by @thewhiteswan 🎉
